### ISSUE TITLE
Errors in borrowed chapter

### ISSUE THREAD

**Issue by Azure-Vani** [nrc/r4cppp#36]
In this chapter, the following code snippet will raise compile error 

    fn foo() {
        let mut x = 5;            // type: int
        {
            let y = &mut x;       // type: &mut int
            //x = 4;              // Error - x has been borrowed
            //println!("{}", x);  // Error - requires borrowing x
            let z = *y + x;       // Ok - doesn't require borrowing
        }
        x = 4;                    // OK - y no longer exists
    }

**Comment by nrc** [comment]
So, this is actually a little bit interesting. It didn't used to be an error, but now is. I wasn't sure if this was a bug fix or a regression. I think it is the former - we used to treat arithmetic on numbers specially, but we no longer do. Just because `x` is `Copy` doesn't mean we can use it when it is mutably borrowed - since `Copy` does not ensure that a value is atomically updated, that would allow us to observe `x` in a potentially inconsistent state.
